### ISSUE TITLE
Wrong shm size in deployment pod when inference model with multi gpu

### ISSUE THREAD

**Issue by tuanhm-3488** [vllm-project/production-stack#276]
**When i install helm with this config to deploy multiple gpu inference application, i caught an error about creating shared memory segment **

`torch.distributed.DistBackendError: NCCL error in: ../torch/csrc/distributed/c10d/NCCLUtils.hpp:317, unhandled system error (run with NCCL_DEBUG=INFO for details), NCCL version 2.21.5
ncclSystemError: System call (e.g. socket, malloc) or external library call failed or device error. 
Last error:
Error while creating shared memory segment /dev/shm/nccl-F9ffgB (size 9637888)`

**I think the error came from the shm size. Then i have defined shmSize in yaml config below:**
`servingEngineSpec:
  runtimeClassName: ""
  modelSpec:
  - name: "opt125m"
    repository: "vllm/vllm-openai"
    tag: "latest"
    modelURL: "facebook/opt-125m"

    replicaCount: 1

    requestCPU: 6
    requestMemory: "16Gi"
    requestGPU: 2

    vllmConfig:
      maxModelLen: 200
      dtype: "bfloat16"
      extraArgs: ["--disable-log-requests", "--gpu-memory-utilization", "0.1", "--tensor-parallel-size", "2"]

    shmSize: "20Gi"`

**But when i check shm size in deployment pod with command, it showed that my shm size in container pod only has 64MB:**
`kubectl exec -it vllm-deployment-router-8666bf6464-jn224 -- df -h /dev/shm
Filesystem      Size  Used Avail Use% Mounted on
shm              64M     0   64M   0% /dev/shm`

**How can i deal with that? Thanks in advance**

**Comment by YuhanLiu11** [comment]
hey @tuanhm-3488 thanks for submitting the issue. I'll try to reproduce this error soon!

**Comment by tuanhm-3488** [comment]
@YuhanLiu11 Thank you for your reply, i have fixed this before. However, i want to deploy LLM model on multi gpu multi node via Leader work set (LWS), do your team have a plan to integrate this function in the future?
