### ISSUE TITLE
GPU not detected inside kind cluster on WSL 2 when install it

### ISSUE THREAD

**Issue by pzy0006** [vllm-project/production-stack#620]
Hi all 👋,

I’m following tutorials/00‑c‑install-kind-kubernetes-env.md on WSL 2 (Ubuntu 20.04).
The host GPU/driver work fine (nvidia‑smi prints OK, Docker GPU containers run), but inside the kind cluster the node never advertises a GPU, so every pod says “NVIDIA Driver was not detected.”

### **Environment**
Host OS  -- WSL2 Ubuntu 20.04
GPU        --  RTX 5070TI
Docker    --  Docker Engine 28.3.2

### **Steps to reproduce**
```
git clone https://github.com/vllm-project/production-stack.git
cd production-stack/utils
bash install-kind-cluster.sh            # finishes with no errors
Setting NVIDIA container toolkit (nvidia-ctk) to be docker's default runtime...
INFO[0000] Loading config from /etc/docker/daemon.json
INFO[0000] Wrote updated config to /etc/docker/daemon.json
INFO[0000] It is recommended that docker daemon be restarted.
Restarting docker...
Allowing volume mounts...
Creating cluster "single-node-cluster" ...
 ✓ Ensuring node image (kindest/node:v1.27.3) 🖼
 ✓ Preparing nodes 📦
 ✓ Writing configuration 📜
 ✓ Starting control-plane 🕹️
 ✓ Installing CNI 🔌
 ✓ Installing StorageClass 💾
Set kubectl context to "kind-single-node-cluster"
You can now use your cluster with:

kubectl cluster-info --context kind-single-node-cluster

Have a question, bug, or feature request? Let us know! https://kind.sigs.k8s.io/#community 🙂
Adding nvidia helm repo and installing its gpu-operator helm chart...
"nvidia" already exists with the same configuration, skipping
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "nvidia" chart repository
Update Complete. ⎈Happy Helming!⎈
NAME: gpu-operator-1753847087
LAST DEPLOYED: Tue Jul 29 23:44:48 2025
NAMESPACE: gpu-operator
STATUS: deployed
REVISION: 1
TEST SUITE: None
```

`kubectl describe node | grep -i nvidia.com/gpu   # → nothing`
```
kubectl describe nodes | grep -i gpu
  gpu-operator                gpu-operator-1753847087-node-feature-discovery-gc-64f7dd96pgkgh    10m (0%)      0 (0%)      128Mi (0%)       1Gi (6%)       28m
  gpu-operator                gpu-operator-1753847087-node-feature-discovery-master-85f8dxb75    100m (0%)     0 (0%)      128Mi (0%)       4Gi (26%)      28m
  gpu-operator                gpu-operator-1753847087-node-feature-discovery-worker-lwp65        5m (0%)       0 (0%)      64Mi (0%)        512Mi (3%)     28m
  gpu-operator                gpu-operator-f9b48d7c9-l7scj   
``` 

```

kubectl get daemonset -n gpu-operator \
  nvidia-device-plugin-daemonset                 # → NotFound
```
```

kubectl run gpu-test --image=nvidia/cuda:12.2.0-runtime-ubuntu20.04 \
  --restart=Never -- nvidia-smi
kubectl logs gpu-test

==========
== CUDA ==
==========

CUDA Version 12.2.0

Container image Copyright (c) 2016-2023, NVIDIA CORPORATION & AFFILIATES. All rights reserved.

This container image and its contents are governed by the NVIDIA Deep Learning Container License.
By pulling and using the container, you accept the terms and conditions of this license:
https://developer.nvidia.com/ngc/nvidia-deep-learning-container-license

A copy of this license is made available in this container at /NGC-DL-CONTAINER-LICENSE for your convenience.

WARNING: The NVIDIA Driver was not detected.  GPU functionality will not be available.
   Use the NVIDIA Container Toolkit to start this container with GPU support; see
   https://docs.nvidia.com/datacenter/cloud-native/ .

/opt/nvidia/nvidia_entrypoint.sh: line 67: exec: nvidia-smi: not found
```
```
nvidia-smi #→ Found
Wed Jul 30 00:14:49 2025
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 575.64.04              Driver Version: 577.00         CUDA Version: 12.9     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 5070 Ti     On  |   00000000:01:00.0  On |                  N/A |
|  0%   45C    P8             17W /  300W |    1375MiB /  16303MiB |      4%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI              PID   Type   Process name                        GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|  No running processes found                                                             |
```

### **Actual vs. expected**
**Actual:**

Node capacity lists 0 GPUs; 

**Expected:**

Node advertises nvidia.com/gpu: 1.

### **Ask**
Has anyone solved this on WSL 2?

A working example YAML or script would be greatly appreciated.
Thanks in advance for any pointers! 🙏

**Comment by pzy0006** [comment]
This issue has been solved

**Comment by June24-Wu** [comment]
Hi, want to know how you solve this issue. I am facing the same issue.
